openapi: "3.0.0"
info:
  title: "Minha API"
  version: "1.0.0"
paths:
  /fiap-teste:
    get:
      summary: "Exemplo de endpoint"
      responses:
        "200":
          description: "Resposta bem-sucedida"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MyModel"
components:
  schemas:
    MyModel:
      type: object
      properties:
        message:
          type: string